### ISSUE TITLE
Exception when Ecommerce cron runs

### ISSUE THREAD

**Issue by maderlock** [mailchimp/mc-magento2#108]
**Pre-condition**

* Extension v1.0.24
* Magento 2.1.9

**Steps**

* Enable in config and turn on ecommerce syncing
* Start cron job syncing

**Expected result**

* Sync will run multiple times, updating customers, products etc.

**Actual result**

* Sync runs multiple times, updating customers, products etc.
* Then at some point it starts crashing out and then crashes every time with this message:

    [RuntimeException]
    Cron-job "ebizmarts_ecommerce" threw exception 
    Magento\Framework\Exception\NoSuchEntityException

    [Magento\Framework\Exception\NoSuchEntityException]
    Requested product doesn't exist

I'm not sure at what point this occurs as the runtime exception does not seem to be logged.

I would not be surprised if orders exist for products that have since been deleted. That's pretty normal on a Magento site, which is why so many product details are stored against order items.

**Comment by gonzaloebiz** [comment]
Hi @maderlock 

thanks for your feedback.
This is already fixed.

Best

**Comment by maderlock** [comment]
Just deployed 1.0.25 and still get the same issue. Was this fixed for the latest release?

**Comment by maderlock** [comment]
Here is what I'm seeing in the cron schedule:

![screenshot 2017-11-08 10 54 17](https://user-images.githubusercontent.com/630320/32545316-34ded0aa-c473-11e7-83cf-9a4cd48d2479.png)

**Comment by gabrieljadeau** [comment]
Hi,

Having the same problem here. I have 1000 instance of ebizmarts_ecommerce running in the crontab. Why is the cron running if another instance is already? Do you need me to provide you some more data in order to get it fixed ?

Thanks in avance for your help, that's quite urgent.
