### ISSUE TITLE
Email for abandoned cart sent by MailChimp campaign doesn't show the image of configurable products

### ISSUE THREAD

**Issue by SamueleMartini** [mailchimp/mc-magento2#386]
### Preconditions

    1. Magento CE 2.2.0
    2. mc-magento2 1.0.30.
    3. Abandoned cart option is enable
    4. Parent configurable products has images, associated children simple product doesn't have images.
    5. Campaign for abandoned cart is created in MailChimp and its design has the product grid block

### Steps to reproduce

    1. Navigate to storefront as a registered and logged user.
    2. Add a configurable product to cart.
    3. Navigate cart and proceed to checkout.
    4. Exit from site without placing order, to trigger "abandoned cart" event.
    5. Wait the abandoned cart email setn by MailChimp
    6. Email hasn't images, the <img> tag hasn't the src attribute.

### Actual and Expected result

Expected result:
If simple product doesn't have an imageand it is a child of configurable product, the module should make a fallback on parent configurable product image and send it to MailChimp to populate the imaes in abandoned cart email.

Actual result:
Email for abandoned cart sent by MailChimp campaigns doesn't show the images of configurable products in case the associated simple product doesn't have an own image.

### Additional information

See attched screenshot
![screen shot 2018-09-10 at 15 53 01](https://user-images.githubusercontent.com/40766441/45301710-c5a81a80-b511-11e8-9c53-4b8d672eff21.png)

**Comment by gonzaloebiz** [comment]
Hi @SamueleMartini 

thanks for your feedback.
This issue was already fixed in https://github.com/mailchimp/mc-magento2/issues/307
Try to re sync the products.

Best

**Comment by punkstar** [comment]
The problem solved in #307 appears to have been released in 1.0.29. The OP says that they're running 1.0.30 and I'm experiencing this issue on 1.0.29!

**Comment by SamueleMartini** [comment]
@gonzaloebiz I'm runngin v1.0.30 and the bug is still present.
I have tried to resync products but this operation doesn't solve the problem.
I have tried to delete products in MailChimp and re-import all, but also this operation doesn't solve the problem for abandoned cart automation.

Regards.

**Comment by punkstar** [comment]
@SamueleMartini We're still testing, but this patch looks promising for us.

```
--- ../vendor/mailchimp/mc-magento2/Model/Api/Product.php
+++ ../vendor/mailchimp/mc-magento2/Model/Api/Product.php
@@ -356,7 +356,7 @@
         $data["id"] = $product->getId();
         $data["title"] = $product->getName();
         $data["url"] = $product->getProductUrl();
-        if ($product->getImage()) {
+        if ($product->getImage() && $product->getImage() != 'no_selection') {
             $filePath = 'catalog/product'.$product->getImage();
             $data["image_url"] = $this->_helper->getBaserUrl($magentoStoreId, \Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$filePath;
         } elseif ($this->_parentImage) {
--- ../vendor/mailchimp/mc-magento2/Model/Api/Cart.php	2018-09-14 11:50:03.000000000 +0100
+++ ../vendor/mailchimp/mc-magento2/Model/Api/Cart.php	2018-09-14 15:04:05.000000000 +0100
@@ -450,7 +450,7 @@
             //id can not be 0 so we add 1 to $itemCount before setting the id.
             $itemCount++;
             $line['id'] = (string)$itemCount;
-            $line['product_id'] = $variantId;
+            $line['product_id'] = $item->getProductId();
             $line['product_variant_id'] = $variantId;
             $line['quantity'] = (int)$item->getQty();
             $line['price'] = $item->getPrice();
```

**Comment by SamueleMartini** [comment]
> @SamueleMartini We're still testing, but this patch looks promising for us.
> 
> ```
> --- ../vendor/mailchimp/mc-magento2/Model/Api/Product.php
> +++ ../vendor/mailchimp/mc-magento2/Model/Api/Product.php
> @@ -356,7 +356,7 @@
>          $data["id"] = $product->getId();
>          $data["title"] = $product->getName();
>          $data["url"] = $product->getProductUrl();
> -        if ($product->getImage()) {
> +        if ($product->getImage() && $product->getImage() != 'no_selection') {
>              $filePath = 'catalog/product'.$product->getImage();
>              $data["image_url"] = $this->_helper->getBaserUrl($magentoStoreId, \Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$filePath;
>          } elseif ($this->_parentImage) {
> --- ../vendor/mailchimp/mc-magento2/Model/Api/Cart.php	2018-09-14 11:50:03.000000000 +0100
> +++ ../vendor/mailchimp/mc-magento2/Model/Api/Cart.php	2018-09-14 15:04:05.000000000 +0100
> @@ -450,7 +450,7 @@
>              //id can not be 0 so we add 1 to $itemCount before setting the id.
>              $itemCount++;
>              $line['id'] = (string)$itemCount;
> -            $line['product_id'] = $variantId;
> +            $line['product_id'] = $item->getProductId();
>              $line['product_variant_id'] = $variantId;
>              $line['quantity'] = (int)$item->getQty();
>              $line['price'] = $item->getPrice();
> ```

@punkstar thank you, we will try your patch and I'll give you a feedback.
