### ISSUE TITLE
Abandoned carts not sending

### ISSUE THREAD

**Issue by Kershrew** [mailchimp/mc-magento2#467]
## Title
Abandoned carts not sending

### Preconditions

1. Magento CE 2.2.6
2. mc-magento 1.0.30
3. Mailchimp account setup correctly

### Steps to reproduce

1. Sync store with Mailchimp
2. Setup abandoned cart automation in Mailchimp
3. Go to checkout with a product on store and leave site

### Actual and Expected result

Expected result:
Receive abandoned cart email 1 hour later

Actual result:
Receive nothing.

### Additional information

I have been going over the logs whilst trying to resolve this issue and these entries have been showing up:
```
[2018-11-07 16:11:32] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us18.api.mailchimp.com/3.0/ecommerce/stores/c24bb41555a0a237bb22c0dc724828d3/customers/4322?fields=email_address] using method [GET]
        Detail: [The requested resource could not be found.]
        Params:
                {"fields":"email_address"}^M
 [] []
[2018-11-07 16:11:33] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us18.api.mailchimp.com/3.0/ecommerce/stores/c24bb41555a0a237bb22c0dc724828d3/customers/4334?fields=email_address] using method [GET]
        Detail: [The requested resource could not be found.]
        Params:
                {"fields":"email_address"}^M
 [] []
[2018-11-07 16:11:34] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us18.api.mailchimp.com/3.0/ecommerce/stores/c24bb41555a0a237bb22c0dc724828d3/customers/4288?fields=email_address] using method [GET]
        Detail: [The requested resource could not be found.]
        Params:
                {"fields":"email_address"}^M
 [] []
[2018-11-07 16:11:35] MailChimpLogger.INFO: Resource Not Found for Api Call: [https://us18.api.mailchimp.com/3.0/ecommerce/stores/c24bb41555a0a237bb22c0dc724828d3/customers/4344?fields=email_address] using method [GET]
        Detail: [The requested resource could not be found.]
        Params:
                {"fields":"email_address"}^M
 [] []
```
AND:
```
[2018-11-07 05:11:55] MailChimpLogger.INFO: Invalid Resource for Api Call: [https://us18.api.mailchimp.com/3.0/batches] using method [POST]
	Detail: [The resource submitted could not be validated. For field-specific details, see the 'errors' array.]
	Errors:
		 field [operations.item:283] : Schema describes object, array found instead
		 field [operations.item:287] : Schema describes object, array found instead
		 field [operations.item:288] : Schema describes object, array found instead
		 field [operations.item:294] : Schema describes object, array found instead
		 field [operations.item:295] : Schema describes object, array found instead
		 field [operations.item:296] : Schema describes object, array found instead
		 field [operations.item:298] : Schema describes object, array found instead
		 field [operations.item:300] : Schema describes object, array found instead
		 field [operations.item:301] : Schema describes object, array found instead
		 field [operations.item:302] : Schema describes object, array found instead
		 field [operations.item:303] : Schema describes object, array found instead
		 field [operations.item:308] : Schema describes object, array found instead
		 field [operations.item:313] : Schema describes object, array found instead
		 field [operations.item:315] : Schema describes object, array found instead
		 field [operations.item:318] : Schema describes object, array found instead
		 field [operations.item:320] : Schema describes object, array found instead
		 field [operations.item:321] : Schema describes object, array found instead
		 field [operations.item:329] : Schema describes object, array found instead
		 field [operations.item:330] : Schema describes object, array found instead
		 field [operations.item:334] : Schema describes object, array found instead
		 field [operations.item:336] : Schema describes object, array found instead
		 field [operations.item:337] : Schema describes object, array found instead
		 field [operations.item:339] : Schema describes object, array found instead
		 field [operations.item:341] : Schema describes object, array found instead
		 field [operations.item:346] : Schema describes object, array found instead
		 field [operations.item:347] : Schema describes object, array found instead
		 field [operations.item:351] : Schema describes object, array found instead
		 field [operations.item:353] : Schema describes object, array found instead
		 field [operations.item:355] : Schema describes object, array found instead
		 field [operations.item:357] : Schema describes object, array found instead
		 field [operations.item:360] : Schema describes object, array found instead
		 field [operations.item:362] : Schema describes object, array found instead
		 field [operations.item:364] : Schema describes object, array found instead
		 field [operations.item:366] : Schema describes object, array found instead
		 field [operations.item:367] : Schema describes object, array found instead
		 field [operations.item:368] : Schema describes object, array found instead
		 field [operations.item:370] : Schema describes object, array found instead
		 field [operations.item:371] : Schema describes object, array found instead
		 field [operations.item:372] : Schema describes object, array found instead
		 field [operations.item:373] : Schema describes object, array found instead
		 field [operations.item:378] : Schema describes object, array found instead
		 field [operations.item:386] : Schema describes object, array found instead
		 field [operations.item:388] : Schema describes object, array found instead
		 field [operations.item:389] : Schema describes object, array found instead
		 field [operations.item:390] : Schema describes object, array found instead
		 field [operations.item:392] : Schema describes object, array found instead
		 field [operations.item:396] : Schema describes object, array found instead
		 field [operations.item:398] : Schema describes object, array found instead
		 field [operations.item:399] : Schema describes object, array found instead
		 field [operations.item:403] : Schema describes object, array found instead
		 field [operations.item:404] : Schema describes object, array found instead
		 field [operations.item:406] : Schema describes object, array found instead
		 field [operations.item:408] : Schema describes object, array found instead
		 field [operations.item:415] : Schema describes object, array found instead
		 field [operations.item:417] : Schema describes object, array found instead
		 field [operations.item:422] : Schema describes object, array found instead
		 field [operations.item:424] : Schema describes object, array found instead
		 field [operations.item:428] : Schema describes object, array found instead
		 field [operations.item:429] : Schema describes object, array found instead
		 field [operations.item:431] : Schema describes object, array found instead
		 field [operations.item:432] : Schema describes object, array found instead
		 field [operations.item:434] : Schema describes object, array found instead
		 field [operations.item:436] : Schema describes object, array found instead
		 field [operations.item:437] : Schema describes object, array found instead
		 field [operations.item:439] : Schema describes object, array found instead
		 field [operations.item:440] : Schema describes object, array found instead
		 field [operations.item:441] : Schema describes object, array found instead
		 field [operations.item:443] : Schema describes object, array found instead
		 field [operations.item:452] : Schema describes object, array found instead
		 field [operations.item:455] : Schema describes object, array found instead
		 field [operations.item:460] : Schema describes object, array found instead
		 field [operations.item:472] : Schema describes object, array found instead
		 field [operations.item:475] : Schema describes object, array found instead
		 field [operations.item:476] : Schema describes object, array found instead
		 field [operations.item:480] : Schema describes object, array found instead
		 field [operations.item:481] : Schema describes object, array found instead
		 field [operations.item:482] : Schema describes object, array found instead
		 field [operations.item:487] : Schema describes object, array found instead
		 field [operations.item:490] : Schema describes object, array found instead
		 field [operations.item:492] : Schema describes object, array found instead
		 field [operations.item:493] : Schema describes object, array found instead
		 field [operations.item:495] : Schema describes object, array found instead
		 field [operations.item:497] : Schema describes object, array found instead
		 field [operations.item:498] : Schema describes object, array found instead
		 field [operations.item:503] : Schema describes object, array found instead
		 field [operations.item:504] : Schema describes object, array found instead
		 field [operations.item:506] : Schema describes object, array found instead
		 field [operations.item:508] : Schema describes object, array found instead
		 field [operations.item:509] : Schema describes object, array found instead
		 field [operations.item:511] : Schema describes object, array found instead
		 field [operations.item:513] : Schema describes object, array found instead
		 field [operations.item:517] : Schema describes object, array found instead
		 field [operations.item:521] : Schema describes object, array found instead
		 field [operations.item:527] : Schema describes object, array found instead
		 field [operations.item:535] : Schema describes object, array found instead
		 field [operations.item:554] : Schema describes object, array found instead
		 field [operations.item:556] : Schema describes object, array found instead
		 field [operations.item:558] : Schema describes object, array found instead
```
Above error is followed by a massive amount of data which is sent across and contains sensitive information.

**Comment by gonzaloebiz** [comment]
Hi @Kershrew 

please take  a look at https://github.com/mailchimp/mc-magento2/issues/409
That's why "mc-magento latest version" has no sense, you MUST specify the version that you have

Best

**Comment by Kershrew** [comment]
Thanks, I have updated with the correct version number that is no reason to close my issue off though...

**Comment by gonzaloebiz** [comment]
Update to the current version, today we released a new one

**Comment by Kershrew** [comment]
Will just updating suffice or do I need to perform any other actions?
I have just updated and waiting to see results.

Also, my issue is still closed and I have not had confirmation that a resolution has been reached....

**Comment by gonzaloebiz** [comment]
update the extension is enough to fix it

**Comment by Kershrew** [comment]
I have had abandoned carts since updating and nothing is going through still.

**Comment by Kershrew** [comment]
Hello??
This is still an issue they ARE NOT sending and my issue remains closed??

**Comment by gonzaloebiz** [comment]
Please share your complete configuration screen hiding sensible data like your API key

Best

**Comment by Kershrew** [comment]
![www hervia com_admin_1ti3x1_admin_system_config_edit_section_mailchimp_key_3aadee8762cb103ddca4c6d7e3dda5d8af8a5d240baacb3272730e955a371b6d_](https://user-images.githubusercontent.com/5272683/48264499-9f273280-e421-11e8-90dc-f09f6ff660cb.png)

**Comment by Kershrew** [comment]
![admin_system_config_edit_section_mailchimp_key_3aadee8762cb103ddca4c6d7e3dda5d8af8a5d240baacb3272730e955a371b6d_](https://user-images.githubusercontent.com/5272683/48264548-c251e200-e421-11e8-84aa-3451a8c671fc.png)

**Comment by Kershrew** [comment]
![admin_system_config_edit_section_mailchimp_key_3aadee8762cb103ddca4c6d7e3dda5d8af8a5d240baacb3272730e955a371b6d_](https://user-images.githubusercontent.com/5272683/48264574-dac1fc80-e421-11e8-88a3-4810c5f24d17.png)

**Comment by gonzaloebiz** [comment]
As i can see 9 carts was synced.
If you have problems with the abandoned cart automation, please send an email to our support and we will be pleased to help you.

Best

**Comment by Kershrew** [comment]
Those 9 carts were synced 2 months ago when we tested this on our staging environment, since then I have removed the store from Mailchimp and removed the api keys from Magento then set the store back up with Mailchimp and Magento with new API keys and then set up the new automation which has never worked.

How do I contact support?

Just because you can see that 9 carts were synced it does not mean that this is working, we've had 11 abandoned carts in the past day alone!!

**Comment by gonzaloebiz** [comment]
@Kershrew 

when you remove an store, all the data from this store was deleted, included the carts, when you define a new mailchimp store this has no data (so no carts). So, this 9 carts are synced since you define this new mailchimp store.
Each time that the cron process runs, you can view in the log a summary of the synced object on this run

If you read the home page of this repo, you can find how to contact us.

Best

**Comment by Kershrew** [comment]
Hi @gonzaloebiz 

I 100% removed the stores both from Magento and Mailchimp and it pulled this data back in after I did that.

All I can see in the log now is dozens of entries that look like this:
```
[2018-11-08 19:46:51] MailChimpLogger.INFO: Invalid Resource for Api Call: [https://us18.api.mailchimp.com/3.0/lists/9428f21c02/members/69469a5c4f6e60f5df824df7fb958b3a] using method [PUT]
        Detail: [********@gmail.com has signed up to a lot of lists very recently; we're not allowing more signups for now]
{"status":"pending","email_address":"********@gmail.com","status_if_new":"pending"}^M
 [] []
```
Looks like there's around 60 entries that have this and that's all that has been listed since updating yesterday
